name: Test build and deploy

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/pages-build.yml"
      - ".github/workflows/pr-clean.yml"
      - ".gitignore"
      - "CNAME"
      - "LICENSE.txt"
      - "README.md"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-basepath:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/_get_basepath.yml

  build:
    runs-on: ubuntu-latest
    needs: [get-basepath]
    env:
      base_path: ${{ needs.get-basepath.outputs.base_path }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Patch link
        run: |
          sed -i "s#https://seoklab.org#https://cluster.seoklab.org:8443#g" _config.yml

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - run: bundle exec jekyll build -b "$base_path"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: [self-hosted, galaxy3]
    needs: [get-basepath, build]
    env:
      base_path: ${{ needs.get-basepath.outputs.base_path }}
    steps:
      - name: Make directory
        run: mkdir -p ~/www/html/"$base_path"

      - uses: actions/download-artifact@v3
        id: download
        with:
          name: github-pages

      - name: Extract artifact
        run: tar -C ~/www/html/"$base_path" -xvf ${{ steps.download.outputs.download-path }}/artifact.tar

  comment:
    needs: [get-basepath]
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for your contribution! Your changes will be reflected in <https://cluster.seoklab.org:8443/${{ needs.get-basepath.outputs.base_path }}>. Please check the link and merge this PR if everything is fine.'
            });
