name: Cleanup sites if a PR is closed

on:
  pull_request:
    branches:
      - master
    types:
      - closed

defaults:
  run:
    shell: bash

jobs:
  get-basepath:
    uses: ./.github/workflows/_get_basepath.yml

  clean:
    runs-on: [self-hosted, galaxy3]
    needs: [get-basepath]
    env:
      base_path: ${{ needs.get-basepath.outputs.base_path }}
    steps:
      - name: Remove stale sites
        run: |
          rm -rvf ~/"$base_path"
