name: Watch GalaxyWeb service

on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: "*/5 * * * *"

defaults:
  run:
    shell: bash

concurrency:
  group: galaxyweb-watcher
  cancel-in-progress: ${{ github.event_name != 'schedule' }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - run: |
          export TZ="Asia/Seoul"

          while true; do
            for i in {1..5}; do
              datestr="$(date '+%Y-%m-%dT%H:%M:%S%z')"
              status="$(curl -sSLI https://galaxy.seoklab.org -o /dev/null -w '%{http_code}')"

              if [[ $status == 200 ]]; then
                echo "${datestr} GalaxyWeb is up and running."
                break
              fi

              if [[ $i -eq 5 ]]; then
                echo "${datestr} GalaxyWeb is down after $i attempts. Exiting with failure."
                exit 1
              fi

              echo "Attempt $i: GalaxyWeb is down ($status). Retrying in 10 seconds..."
              sleep 10
            done

            sleep 60
          done

  notify:
    runs-on: ubuntu-latest

    needs: check
    if: ${{ failure() }}

    environment:
      name: galaxyweb-watcher

    steps:
      - run: |
          curl -fsSL -X PATCH "$CF_API_ENDPOINT" -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type:application/json" -d "$CF_API_PAYLOAD" -o /dev/null
        env:
          CF_API_ENDPOINT: ${{ vars.CF_API_ENDPOINT }}
          CF_API_PAYLOAD: ${{ vars.CF_API_PAYLOAD }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - run: |
          curl -fsSL -X POST "$SLACK_API_ENDPOINT" -H "Content-Type: application/json" -d '{"action-id": "${{ github.run_id }}"}' -o /dev/null
        env:
          SLACK_API_ENDPOINT: ${{ secrets.SLACK_API_ENDPOINT }}
