name: Watch GalaxyWeb service

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

defaults:
  run:
    shell: bash

concurrency:
  group: galaxyweb-watcher

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - run: |
          for i in {1..5}; do
            status="$(curl -sSLI https://galaxy.seoklab.org -o /dev/null -w '%{http_code}')"

            if [[ $status == 200 ]]; then
              echo "GalaxyWeb is up and running."
              exit 0
            fi

            echo "Attempt $i: GalaxyWeb is down ($status). Retrying in 10 seconds..."
            sleep 10
          done

  notify:
    runs-on: ubuntu-latest

    needs: check
    if: ${{ failure() }}

    environment:
      name: galaxyweb-watcher

    steps:
      - run: |
          curl -X PATCH "$CF_API_ENDPOINT" -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type:application/json" -d "$CF_API_PAYLOAD"
        env:
          CF_API_ENDPOINT: ${{ vars.CF_API_ENDPOINT }}
          CF_API_PAYLOAD: ${{ vars.CF_API_PAYLOAD }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - run: |
          curl -X POST "$SLACK_API_ENDPOINT" -H "Content-Type: application/json" -d '{"action-id": "${{ github.run_id }}"}'
        env:
          SLACK_API_ENDPOINT: ${{ secrets.SLACK_API_ENDPOINT }}
